### ISSUE TITLE
seth FBX broken

### ISSUE THREAD

**Issue by SN-phaedra** [jade-chamber/sleepy-anime-game-assets#1]
Seth's FBX has no weighting or blendshapes upon being imported into blender or other model editing softwares.

**Comment by GneissFrog** [comment]
for anyone running into a similar issue, use BetterFBX instead of Blender's built-in FBX importer.

**Comment by qilinmoe** [comment]
^
Just use BetterFBX.

BetterFBX should be used while importing any datamined hoyoverse assets, as it will have the necessary features to support the models properly
